# https://pre-commit.com/hooks.html

repos:
  - repo: local
    hooks:
      - id: python-versions
        name: python versions
        entry: python-versions-hook
        language: python
        files: |-
          (?x)^(
            (
            |.*/)pyproject\.toml
            |python_versions_hook/__init__\.py
          )$
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit
    rev: v4.1.0
    hooks:
      - id: validate_manifest
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-ast
      - id: debug-statements
      - id: name-tests-test
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-json
  - repo: https://github.com/PyCQA/prospector
    rev: v1.14.1
    hooks:
      - id: prospector
        args:
          - --tool=ruff
          - --die-on-tool-error
          - --output-format=pylint
          - --profile=.prospector.yaml
          - --profile=utils:autofix
        additional_dependencies:
          - prospector-profile-duplicated==1.10.4 # pypi
          - prospector-profile-utils==1.21.7 # pypi
          - ruff==0.9.9 # pypi
      - id: prospector
        args:
          - --die-on-tool-error
          - --output-format=pylint
          - --profile=utils:tests
          - --profile=utils:autofix
        additional_dependencies:
          - prospector-profile-utils==1.21.7 # pypi
          - ruff==0.9.9 # pypi
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args:
          - --ignore-words=.github/spell-ignore-words.txt
        exclude: ^poetry.lock$
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.4.2 # npm
          - prettier-plugin-sh@0.14.0 # npm
          - prettier-plugin-toml@2.0.2 # npm
        exclude: |-
          (?x)^(
              \.gitattributes
              |\.gitignore
          )$
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: git-check
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.31.2
    hooks:
      - id: check-github-workflows
      - id: check-github-actions
      - id: check-jsonschema
        name: Check GitHub Workflows set timeout-minutes
        files: ^\.github/workflows/[^/]+$
        types:
          - yaml
        args:
          - --builtin-schema
          - github-workflows-require-timeout
  - repo: https://github.com/sirwart/ripsecrets.git
    rev: v0.1.8
    hooks:
      - id: ripsecrets
  - repo: https://github.com/sbrunner/hooks
    rev: 1.2.1
    hooks:
      - id: copyright
      - id: workflows-require-timeout
      - id: poetry-lock
        additional_dependencies:
          - poetry==2.0.1 # pypi
  - repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.8
    hooks:
      - id: ripsecrets
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 39.146.1
    hooks:
      - id: renovate-config-validator
  - repo: https://github.com/sbrunner/jsonschema-validator
    rev: 1.0.0
    hooks:
      - id: jsonschema-validator
        files: |-
          (?x)^(
            \.github/ghci\.yaml
            |\.github/publish\.yaml
          )$
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
      - id: ruff-format
  - repo: https://github.com/sbrunner/python-versions-hook
    rev: 0.8.0
    hooks:
      - id: python-versions
